def ksFile = rootProject.file("signing.properties")
def props = new Properties()
if (ksFile.canRead()) {
    props.load(new FileInputStream(ksFile))

    if (props != null) {
        project.extensions.getByName("android").signingConfigs.sign.storeFile file(props["KEYSTORE_FILE"])
        project.extensions.getByName("android").signingConfigs.sign.storePassword props["KEYSTORE_PASSWORD"]
        project.extensions.getByName("android").signingConfigs.sign.keyAlias props["KEYSTORE_ALIAS"]
        project.extensions.getByName("android").signingConfigs.sign.keyPassword props["KEYSTORE_ALIAS_PASSWORD"]
    }
} else {
    project.extensions.getByName("android").signingConfigs.sign.storeFile = project.extensions.getByName("android").signingConfigs.debug.storeFile
    project.extensions.getByName("android").signingConfigs.sign.storePassword = project.extensions.getByName("android").signingConfigs.debug.storePassword
    project.extensions.getByName("android").signingConfigs.sign.keyAlias = project.extensions.getByName("android").signingConfigs.debug.keyAlias
    project.extensions.getByName("android").signingConfigs.sign.keyPassword = project.extensions.getByName("android").signingConfigs.debug.keyPassword
}
